name: flight_performance_analytics
version: "1.0.0"
config-version: 2

profile: flight_performance_analytics

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  flight_performance_analytics:
    staging:
      +materialized: table
